summary: Obtener detalle de un producto
description: |
  Recupera toda la información de un producto por su ID.
  Incluye precio, puntos BV, imágenes, descripción, stock, categoría y subcategoría.
tags:
  - 🛍️ Catálogo
parameters:
  - name: id
    in: query
    type: integer
    required: true
    description: ID del producto
    example: 12
responses:
  200:
    description: Producto encontrado
    schema:
      type: object
      properties:
        id_producto:
          type: integer
          example: 12
        nombre:
          type: string
          example: "Smartwatch Modelo Z"
        precio:
          type: number
          example: 199.99
        puntos_bv:
          type: integer
          example: 15
        imagen:
          type: string
          example: "https://dominio.com/uploads/productos/principal.jpg"
        imagenes:
          type: array
          items:
            type: string
          example:
            - "https://dominio.com/uploads/productos/1.jpg"
            - "https://dominio.com/uploads/productos/2.jpg"
        descripcion:
          type: string
          example: "Reloj inteligente con múltiples funciones."
        stock:
          type: integer
          example: 30
        categoria:
          type: string
          example: "Tecnología"
        subcategoria:
          type: string
          example: "Wearables"
  404:
    description: Producto no encontrado
    schema:
      type: object
      properties:
        error:
          type: string
          example: "Producto no encontrado"
  500:
    description: Error interno del servidor
    schema:
      type: object
      properties:
        error:
          type: string
          example: "Error al procesar la solicitud"
