summary: Listar productos activos con stock
description: |
  Devuelve los productos activos con stock mayor a 0.
  Incluye la categoría, subcategoría y datos principales del producto.
tags:
  - 🛍️ Catálogo
responses:
  200:
    description: Productos obtenidos con éxito
    schema:
      type: array
      items:
        type: object
        properties:
          id_producto:
            type: integer
            example: 25
          categoria:
            type: string
            example: "Electrónica"
          subcategoria:
            type: string
            example: "Auriculares"
          nombre:
            type: string
            example: "Audífonos Modelo X"
          precio:
            type: number
            example: 129.99
          puntos_bv:
            type: integer
            example: 20
          imagen:
            type: string
            example: "https://dominio.com/uploads/productos/imagen.jpg"
          stock:
            type: integer
            example: 15
  500:
    description: Error interno al obtener productos
    schema:
      type: object
      properties:
        error:
          type: string
          example: "Error interno al obtener productos"
